
Route::get('/user', function (Request $request) {
    return $request->user();
})->middleware('auth:sanctum');

Route::post('validation',[MPESAResponsesController::class,'validation']);
Route::post('confirmation',[MPESAResponsesController::class,'confirmation']);
//Route::post('stkpush',[MPESAResponsesController::class,'stkPush']);
//Route::post('stkpush',[MPESAResponsesController::class,'stkPush']);
//Route::post('stkpush',[MPESAResponsesController::class,'stkPush']);
//Route::post('stkpush',[MPESAResponsesController::class,'stkPush']);
//Route::post('stkpush',[MPESAResponsesController::class,'stkPush']);
//Route::post('stkpush',[MPESAResponsesController::class,'stkPush']);
//Route::post('stkpush',[MPESAResponsesController::class,'stkPush']);
//Route::post('stkpush',[MPESAResponsesController::class,'stkPush']);
//Route::post('stkpush',[MPESAResponsesController::class,'stkPush']);
//Route::post('stkpush',[MPESAResponsesController::class,'stkPush']);
//Route::post('stkpush',[MPESAResponsesController::class,'stkPush']);
//Route::post('stkpush',[MPESAResponsesController::class,'stkPush']);
//Route::post('stkpush',[MPESAResponsesController::class,'stkPush']);
//Route::post('stkpush',[MPESAResponsesController::class,'stkPush']);
//Route::post('stkpush',[MPESAResponsesController::class,'stkPush']);
//Route::post('stkpush',[MPESAResponsesController::class,'stkPush']);
//Route::post('stkpush',[MPESAResponsesController::class,'stkPush']);
//Route::post('stkpush',[MPESAResponsesController::class,'stkPush']);
//Route::post('stkpush',[MPESAResponsesController::class,'stkPush']);
//Route::post('stkpush',[MPESAResponsesController::class,'stkPush']);
//Route::post('stkpush',[MPESAResponsesController::class,'stkPush']);
//Route::post('stkpush',[MPESAResponsesController::class,'stkPush']);
//Route::post('stkpush',[MPESAResponsesController::class,'stkPush']);
//Route::post('stkpush',[MPESAResponsesController::class,'stkPush']);
//Route::post('stkpush',[MPESAResponsesController::class,'stkPush']);
//Route::post('stkpush',[MPESAResponsesController::class,'stkPush']);
//Route::post('stkpush',[MPESAResponsesController::class,'stkPush']);
//Route::post('stkpush',[MPESAResponsesController::class,'stkPush']);
//Route::post('stkpush',[MPESAResponsesController::class,'stkPush']);
//Route::post('stkpush',[MPESAResponsesController::class,'stkPush']);
//Route::post('stkpush',[MPESAResponsesController::class,'stkPush']);
//Route::post('stkpush',[MPESAResponsesController::class,'stkPush']);
//Route::post('stkpush',[MPESAResponsesController::class,'stkPush']);
//Route::post('stkpush',[MPESAResponsesController::class,'stkPush']);
//Route::post('stkpush',[MPESAResponsesController::class,'stkPush']);
//Route::post('stkpush',[MPESAResponsesController::class,'stkPush']);
//Route::post('stkpush',[MPESAResponsesController::class,'stkPush']);
//Route::post('stkpush',[MPESAResponsesController::class,'stkPush']);
//Route::post('stkpush',[MPESAResponsesController::class,'stkPush']);
//Route::post('stkpush',[MPESAResponsesController::class,'stkPush']);
//Route::post('stkpush',[MPESAResponsesController::class,'stkPush']);
